package editor.core.enums;

public enum AI_Type {
	//SHIPS
	SENTRY,
	LIFE_SUPPORT,
	ANTI_LIFE_SUPPORT,
	SHIP_SPAWNER,
	AUTOREPAIR,
	EXPLORER,
	SHIP_HUNTER,
	SHIP_CLASS_HUNTER,
	RACE_HUNTER,
	MOB_HUNTER,
	LEVEL_LOADER,
	SECTOR_FINDER,
	ROGUE_AI_OWNER,
	PIRATE_OWNER,
	TRADER_OWNER,
	TRADER,
	ENEMY_SHOOTER,
	SHIP_GUARD,
	EVENT_TRIGGER,
	EVADER,
	POSITIONER,
	SCAVENGER,
	PEACE_KEEPER,
	BOARDING_MANAGER,
	//MOBS
	NPC_REPAIRMAN,
	NPC_LIFESUPPORT,
	NPC_FIREMAN,
	NPC_TALKER,
	NPC_WORKER,
	NPC_DEFENDER,
	NPC_BOARDER,
	NPC_CLAIMER,
	NPC_EVENT_TRIGGER,
	NPC_CONTROLLED_WORKER;

}
