package editor.core.enums;

public enum ConditionType {
	SHIP_COMBAT_PRESENT,
	SHIP_COMBAT_ABSENT(true),
	SHIP_HULL_PRESENT,
	SHIP_HULL_ABSENT(true),
	SHIP_CARGO_PRESENT,
	SHIP_CARGO_ABSENT(true),
	SHIP_SYSTEM_PRESENT,
	SHIP_SYSTEM_ABSENT(true),
	SHIP_SCRAP_PRESENT,
	SHIP_SCRAP_ABSENT(true),
	SHIP_MISSILES_PRESENT,
	SHIP_MISSILES_ABSENT(true),
	SHIP_DRONES_PRESENT,
	SHIP_DRONES_ABSENT(true),
	SHIP_CREW_PRESENT,
	SHIP_CREW_ABSENT(true),
	SHIP_LEVEL_PRESENT,
	SHIP_LEVEL_ABSENT(true),
	SHIP_POSITION_PRESENT,
	SHIP_POSITION_ABSENT(true),
	SHIP_SHIELDS_PRESENT,
	SHIP_SHIELDS_ABSENT(true),
	SHIP_NAME_PRESENT,
	SHIP_NAME_ABSENT(true),
	SHIP_RACE_PRESENT,
	SHIP_RACE_ABSENT(true),
	SHIP_CLASS_PRESENT,
	SHIP_CLASS_ABSENT(true),
	SHIP_AI_PRESENT,
	SHIP_AI_ABSENT(true),
	MOB_HEALTH_PRESENT,
	MOB_HEALTH_ABSENT(true),
	MOB_NAME_PRESENT,
	MOB_NAME_ABSENT(true),
	MOB_SCRAP_PRESENT,
	MOB_SCRAP_ABSENT(true),
	MOB_OXYGEN_PRESENT,
	MOB_OXYGEN_ABSENT(true),
	MOB_RACE_PRESENT,
	MOB_RACE_ABSENT(true),
	MOB_AI_PRESENT,
	MOB_AI_ABSENT(true),
	SECTOR_TYPE_PRESENT,
	SECTOR_TYPE_ABSENT(true),
	SECTOR_SHIPS_PRESENT,
	SECTOR_SHIPS_ABSENT(true),
	SECTOR_COORDS_PRESENT,
	SECTOR_COORDS_ABSENT(true),
	SECTOR_AREA_PRESENT,
	SECTOR_AREA_ABSENT(true),
	SECTOR_NPCS_PRESENT,
	SECTOR_NPCS_ABSENT(true),
	SECTOR_PLAYERS_PRESENT,
	SECTOR_PLAYERS_ABSENT(true),
	SECTOR_DEBRIS_PRESENT,
	SECTOR_DEBRIS_ABSENT(true),
	SECTOR_THREAT_PRESENT,
	SECTOR_THREAT_ABSENT(true),
	SERVER_VARIABLE_PRESENT,
	SERVER_VARIABLE_ABSENT(true),
	SERVER_VARIABLE_SMALLER(true),
	SERVER_VARIABLE_BIGGER(true);

	public boolean allRequired;

	private ConditionType(boolean all) {
		allRequired = all;
	}

	private ConditionType() {
		
	}
	
}
